---
# This playbook backups all mysql databases into separate files.
#
# How to execute on project root folder
# cd /home/pi/PKC && ansible-playbook -i ./resources/config/host-gasingorg ./resources/ansible-yml/cs-backup-remote.yml
# 
#
- name: Backup Loop
  hosts: all
  gather_facts: yes
  become: yes
  become_user: root

  tasks:
  - name: Execute mysql backup at container on {{ hostvars[inventory_hostname].inventory_hostname }}
    block:
    # - name: Prepare mysql backup command
    #   set_fact:
    #     docker_cmd: "mysqldump --single-transaction --host=database --user=root --password=secret my_wiki | gzip > /mnt/backup_restore/mariadb/{{ ansible_host }}-my_wiki-{{ ansible_date_time.iso8601_basic_short }}.sql.gz; exit $?"
      
    - name: Execute mysql backup wiki
      command: "docker exec -t xlp_mariadb /bin/bash -c 'mysqldump --single-transaction --user=root --password=secret my_wiki | gzip > /mnt/backup_restore/mariadb/{{ ansible_host }}-my_wiki-{{ ansible_date_time.iso8601_basic_short }}.sql.gz; exit $?'"
      become: yes
      register: output

    - name: Execute mysql Moodle backup
      command: "docker exec -t xlp_mariadb /bin/bash -c 'mysqldump --single-transaction --user=root --password=secret moodle | gzip > /mnt/backup_restore/mariadb/{{ ansible_host }}-moodle-{{ ansible_date_time.iso8601_basic_short }}.sql.gz; exit $?'"
      become: yes
      register: output    

    - name: Prepare moodle media backup
      command: "chdir={{ pkc_install_root_dir }}mountpoint/ tar -czvf ./backup_restore/{{ ansible_host }}-moodledata-{{ ansible_date_time.iso8601_basic_short }}.tar.gz ./moodledata"
      register: ls_result

    - name: Execute image backup create folder
      command: "docker exec -t xlp_mediawiki /bin/bash -c 'mkdir /mnt/backup_restore/mediawiki/{{ ansible_date_time.iso8601_basic_short }}'"
      become: yes
      register: output

    - name: Execute image backup create
      command: "docker exec -t xlp_mediawiki /bin/bash -c 'php /var/www/html/maintenance/dumpUploads.php | sed 's~mwstore://local-backend/local-public~./images~' | xargs cp -t /mnt/backup_restore/mediawiki/{{ ansible_date_time.iso8601_basic_short }}'"
      become: yes
      register: output

    - name: Prepare media backup command
      set_fact:
        docker_cmd: "tar -zcvf /mnt/backup_restore/mediawiki/{{ ansible_host }}-{{ ansible_date_time.iso8601_basic_short }}-image.tar.gz -C /mnt/backup_restore/mediawiki/{{ ansible_date_time.iso8601_basic_short }} ."

    - name: print output
      debug:
        msg: "{{ docker_cmd }}"

    - name: Execute image backup tar
      command: "docker exec -t xlp_mediawiki /bin/bash -c '{{ docker_cmd }}'"
      become: yes
      register: output

    - name: Execute image backup remove footprint
      command: "docker exec -t xlp_mediawiki /bin/bash -c 'rm -rf /mnt/backup_restore/mediawiki/{{ ansible_date_time.iso8601_basic_short }}'"
      become: yes
      register: output

    - name: backup retention on source server {{ retention }} day(s)
      command: "find {{ item }} -type f -mtime +{{ retention }} -delete"
      become: yes
      register: output
      loop:
        - "{{ ansible_env.PWD }}/cs/mountpoint/backup_restore/mariadb/"
        - "{{ ansible_env.PWD }}/cs/mountpoint/backup_restore/mediawiki/"

    # when: "inventory_hostname|string == src_server"
    when: "hostvars[inventory_hostname].brl == 'src'"
    run_once: yes
    ignore_errors: yes

  - name: Get backup latest file list set on {{ hostvars[inventory_hostname].inventory_hostname }}
    block:
    # Mediawiki Database Backup------------------------------------------------------------------------
    - name: Get database backup file
      find:
        paths: "{{ ansible_env.PWD }}/cs/mountpoint/backup_restore/mariadb/"
        patterns: '*my_wiki*'
      register: found_files
    
    - name: Get database latest backup file path
      set_fact:
        db_wiki_backup_file_path: "{{ found_files.files | sort(attribute='mtime',reverse=true) | first }}"

    - name: Get database latest backup file
      set_fact:
        db_wiki_backup_file: "{{ db_wiki_backup_file_path.path | basename }}"
    # ------------------------------------------------------------------------------------------------
    # Moodle Database Backup--------------------------------------------------------------------------
    - name: Get database backup file
      find:
        paths: "{{ ansible_env.PWD }}/cs/mountpoint/backup_restore/mariadb/"
        patterns: '*moodle*'
      register: found_files
    
    - name: Get database latest backup file path
      set_fact:
        db_moodle_backup_file_path: "{{ found_files.files | sort(attribute='mtime',reverse=true) | first }}"

    - name: Get database latest backup file
      set_fact:
        db_moodle_backup_file: "{{ db_moodle_backup_file_path.path | basename }}"
    # ------------------------------------------------------------------------------------------------
    # Mediawiki Image Backup--------------------------------------------------------------------------
    - name: Get latest image backup file
      find:
        paths: "{{ ansible_env.PWD }}/cs/mountpoint/backup_restore/mediawiki/"
        patterns: '*image*'
      register: found_files
    
    - name: Get latest image backup file path
      set_fact:
        img_wiki_backup_file_path: "{{ found_files.files | sort(attribute='mtime',reverse=true) | first }}"
        # delegate_to: "{{ item }}"
        # with_items: "{{ play_hosts }}"

    - name: Get latest image backup file
      set_fact:
        img_wiki_backup_file: "{{ img_wiki_backup_file_path.path | basename }}"
        # delegate_to: "{{ item }}"
        # with_items: "{{ play_hosts }}"
    # ------------------------------------------------------------------------------------------------    
    # Moodle folder Backup----------------------------------------------------------------------------
    - name: Get latest moodle backup file
      find:
        paths: "{{ ansible_env.PWD }}/cs/mountpoint/backup_restore/"
        patterns: '*moodle*'
      register: found_files
    
    - name: Get latest image backup file path
      set_fact:
        dir_moodle_backup_file_path: "{{ found_files.files | sort(attribute='mtime',reverse=true) | first }}"
        # delegate_to: "{{ item }}"
        # with_items: "{{ play_hosts }}"

    - name: Get latest image backup file
      set_fact:
        dir_moodle_backup_file: "{{ dir_moodle_backup_file_path.path | basename }}"
        # delegate_to: "{{ item }}"
        # with_items: "{{ play_hosts }}"
    # ------------------------------------------------------------------------------------------------
    - name: print file names without path - image backup
      debug:
        msg: "{{ img_wiki_backup_file }}"

    - name: print file names without path - mediawiki database backup
      debug:
        msg: "{{ db_wiki_backup_file }}"

    - name: print file names without path - moodle database backup
      debug:
        msg: "{{ db_moodle_backup_file }}"

    - name: print file names without path - moodle database backup
      debug:
        msg: "{{ dir_moodle_backup_file }}"        

    #when: "inventory_hostname|string == src_server"
    when: "hostvars[inventory_hostname].brl == 'src'"
    run_once: yes
    become: true
    become_user: root
    ignore_errors: yes
  
  - name: Get backup latest file from {{ hostvars[inventory_hostname].inventory_hostname }} into master
    block:
    # Fetch db-file mediawiki from source
    - name: Fetch the db wiki file from the "{{ hostvars[inventory_hostname].inventory_hostname }}" to master
      fetch: src=/{{ pkc_install_root_dir }}mountpoint/backup_restore/mariadb/{{ db_wiki_backup_file }} dest=../../backup/ flat=yes

    # Fetch db-file moodle from source
    - name: Fetch the db moodle file from the "{{ hostvars[inventory_hostname].inventory_hostname }}" to master
      fetch: src=/{{ pkc_install_root_dir }}mountpoint/backup_restore/mariadb/{{ db_moodle_backup_file }} dest=../../backup/ flat=yes

    # Fetch dir-file moodle from source
    - name: Fetch the dir moodle file from the "{{ hostvars[inventory_hostname].inventory_hostname }}" to master
      fetch: src=/{{ pkc_install_root_dir }}mountpoint/backup_restore/{{ dir_moodle_backup_file }} dest=../../backup/ flat=yes

    # Fetch image-file from source
    - name: Fetch the image file from the "{{ hostvars[inventory_hostname].inventory_hostname }}" to master
      fetch: src=/{{ pkc_install_root_dir }}mountpoint/backup_restore/mediawiki/{{ img_wiki_backup_file }} dest=../../backup/ flat=yes

    #when: "inventory_hostname|string == src_server"
    when: "hostvars[inventory_hostname].brl == 'src'"
    run_once: yes
    become: false
    # become_user:  root
    ignore_errors: yes

  ## Maintain only last x days retention, on source server
  - name: Retention mysql backup to {{ retention }} day(s), on source server
    command: "find {{ ansible_env.PWD }}/cs/mountpoint/backup_restore/mariadb -type f -mtime +{{ retention }} -delete"
    become: yes
    register: output

  - name: Retention image backup to {{ retention }} day(s), on source server
    command: "find {{ ansible_env.PWD }}/cs/mountpoint/backup_restore/mediawiki -type f -mtime +{{ retention }} -delete"
    become: yes
    register: output

  - name: Retention image backup to {{ retention }} day(s), on source server
    command: "find {{ ansible_env.PWD }}/cs/mountpoint/backup_restore -type f -mtime +{{ retention }} -delete"
    become: yes
    register: output