---
- name: install auto-restore process into backup server
  hosts: all
  become: yes

  tasks:
  - name: Upload scripts and config
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      remote_src: yes
      mode: u=rwx,g=rx,o=rx

    loop:
      - {src: '../script/cs-backup.sh', dest: './cs/cs-backup.sh'}
      - {src: '../script/cs-restore.sh', dest: './cs/cs-restore.sh'}
      - {src: '../script/cs-auto-restore.sh', dest: './cs/cs-auto-restore.sh'}
      - {src: '../script/update-sw.sh', dest: './cs/update-sw.sh'}
      - {src: '../script/mtm-sql.sh', dest: './cs/mtm-sql.sh'}
    become: true
    ignore_errors: yes

  - name: Creates hourly entry for auto restore
    ansible.builtin.cron:
      name: "Automatic Hourly PKC Restore"
      minute: "5"
      hour: "*"
      job: "cd /home/ubuntu/cs/ && ./cs-auto-restore.sh >> /home/ubuntu/cs/restore.log"
    ignore_errors: yes
