---
- name: install and provisioning dockers PKC Server on Localhost
  hosts: localhost

  tasks:
  - name: Localhost macOS installation process
    block:

    - name: Check docker installation on localhost machine
      shell: "docker info | grep Docker"
      register: docker_output
      ignore_errors: yes

    - name: Execute Docker-compose
      command: "docker-compose up -d"  

    - name: Execute Update on Hosts file
      command: "../script/update-hosts.sh"
      become: yes

    - name: Check docker installation on localhost machine
      shell: "./resources/script/update-sw.sh || /usr/bin/true"
      register: update_script
      ignore_errors: yes    

    - name: Print debug
      ansible.builtin.debug:
        var: update_script

    when: ansible_facts['os_family'] == "Darwin"
    ignore_errors: yes