---
- name: bring service up after sync
  hosts: all
  become: yes

  tasks:
  - name: Run `docker-compose up` again
    community.docker.docker_compose:
      project_src: cs
      build: no
    register: output

  - name: Execute the update script 
    command: "sh {{ ansible_env.PWD }}/cs/update-sw.sh"
