galaxy_info:
  author: Dmitrii Kashin
  description: role to create cron job, wraps the cron module
  role_name: crontask
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags: [ cron, task ]

dependencies: []
