galaxy_info:
  author: Dmitrii Kashin
  description: install a script performing mysql backups
  role_name: script_mysql_backup
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags: [ mysql, backup, aws, s3, slack ]

dependencies: []
