# ansible-playbook -i hosts cs-backup.yml
---
- name: up and running docker containers
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
  - name: execute backup script
    command: sh -c "{{ ansible_env.PWD }}/cs/cs-backup.sh -w {{ ansible_env.PWD }}/cs/mountpoint"
    become: true
#
# download database file
#
  - name: Get files in a folder
    find:
      paths: "{{ ansible_env.PWD }}/cs/mountpoint/backup_restore/mariadb"
    register: found_files

  - name: Get latest file
    set_fact:
      latest_file: "{{ found_files.files | sort(attribute='mtime',reverse=true) | first }}"

  - name: ansible copy file from remote to local.
    fetch:
      src: "{{ latest_file.path }}"
      dest: "./downloaded/{{ ansible_host }}-mariadb.tar.gz"
      flat: yes
#
# download images file
#
  - name: Get files in a folder
    find:
      paths: "{{ ansible_env.PWD }}/cs/mountpoint/backup_restore/mediawiki"
    register: found_files

  - name: Get latest file
    set_fact:
      latest_file: "{{ found_files.files | sort(attribute='mtime',reverse=true) | first }}"

  - name: ansible copy file from remote to local.
    fetch:
      src: "{{ latest_file.path }}"
      dest: "./downloaded/{{ ansible_host }}-mediawiki.tar.gz"
      flat: yes


