- name: Install PKC HTTPS 
  hosts: all
  become: yes
  vars_files:
    - ./config/default.yml
   
  tasks:
  - name : Install Python Package
    apt: name=python3 update_cache=yes state=latest
 
  - name : Install Let's Encrypt Package
    apt: name={{ certbot_package }} update_cache=yes state=latest
 
  - name: Create and Install Cert Using NGINX Plugin
    command: "certbot --nginx -d  {{ item }} -m {{ certbot_mail_address }} --agree-tos --noninteractive --redirect"
    with_items: 
    - "{{ certbot_domain_name }}"
    - "www.{{ certbot_domain_name }}"
    - "pma.{{ certbot_domain_name }}"
    - "git.{{ certbot_domain_name }}"
    - "mtm.{{ certbot_domain_name }}"
    - "code.{{ certbot_domain_name }}"
    - "kck.{{ certbot_domain_name }}"

  - name: copy Application Configuration Files
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      remote_src: false
    loop:
      - {src: "./config/LocalSettings.php", dest: './cs/mountpoint'}
      - {src: './config/config.ini.php', dest: './cs/mountpoint/matomo/config'}
    become: true

  - name: Set Letsencrypt Cronjob for Certificate Auto Renewal
    cron: name=letsencrypt_renewal special_time=monthly job="/usr/bin/certbot renew"
    when: ansible_facts['os_family'] == "Debian"