---
- name: Restore from server's backup storage
  hosts: all
  become: yes
  vars:
    - backup_scp_host: "pkc-back.org"
    - backup_scp_identity_src: "~/.ssh/OregonCluster.pem"
    - backup_scp_user: 'ubuntu'
    - backup_scp_dst: '/home/ubuntu/cs/mountpoint/backup_restore/mariadb'
    - db_file_backup: 'pkc.pub-my_wiki-2022-02-24-17h01m01s.sql.gz'
    - img_file_backup: 'pkc.pub-2022-02-24-17h01m01s-images.tar.gz'

  tasks:
  - name: Get backup file from backup host
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      remote_src: false
      mode: u=rwx,g=rx,o=rx

    loop:
      - {src: './mountpoint/backup_restore/mariadb/{{ db_file_backup }}', dest: '{{ ansible_env.PWD }}/cs/mountpoint/backup_restore/mariadb'}
      - {src: './mountpoint/backup_restore/mediawiki/{{ img_file_backup }}', dest: '{{ ansible_env.PWD }}/cs/mountpoint/backup_restore/mediawiki'}
    become: true
    
  - name: execute restore to server's target    
    command: sh -c "{{ ansible_env.PWD }}/cs/cs-restore.sh -m {{ ansible_env.PWD }}/cs/mountpoint -d {{ db_file_backup }} -i {{ img_file_backup }}"
    become: true