---
- name: shutting down CS remote service
  hosts: all
  become: yes

  tasks:
  - name: Shut Down existing PKC Service
    community.docker.docker_compose:
      project_src: cs
      state: absent