FROM ubuntu:20.04

ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8

# RUN echo "sysops ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/sysops
# RUN echo "export LC_CTYPE=en_US.UTF-8" >> /root/.bashrc
# RUN echo "export LC_ALL=en_US.UTF-8" >> /root/.bashrc 

RUN apt update; \ 
    apt upgrade -y; \
    apt install -y software-properties-common; \
    add-apt-repository --yes --update ppa:ansible/ansible;

# Install NANO
RUN apt-get install nano

# Fix Locales
RUN apt-get install -y locales
RUN locale-gen en_US.UTF-8

RUN apt-get install -y git
WORKDIR /
RUN git clone https://github.com/xlp0/PKC.git -b dev

RUN apt update
RUN apt install -y ansible

WORKDIR /PKC
