---
mysql_backup_script_dir: "/opt/scripts"
mysql_backup_script_name: "mysql-backup.sh"
mysql_backup_script: "{{ mysql_backup_script_dir }}/{{ mysql_backup_script_name }}"

mysql_backup_custom_script_dir: "{{ mysql_backup_script_dir }}"
mysql_backup_custom_script_name: "mysql-backup-{% if mysql_backup_db == '' %}all{% else %}{{ mysql_backup_db }}{% endif %}.sh"
mysql_backup_custom_script: "{{ mysql_backup_custom_script_dir }}/{{ mysql_backup_custom_script_name }}"

mysql_backup_hostname: "{{ inventory_hostname }}"
mysql_backup_tmpdir: "/tmp"

mysql_backup_host: "localhost"
mysql_backup_port: "3306"
mysql_backup_user: "root"
mysql_backup_pass: ""
mysql_backup_db: ""

mysql_backup_conf_dir: "/etc/mysql_backup"

mysql_backup_backend_use_s3: no
mysql_backup_s3cfg_path: "{{ mysql_backup_conf_dir }}/s3cfg"
#mysql_backup_s3cfg_template: "s3cfg.j2"
#mysql_backup_s3:
#  username: "s3user"
#  access_key: "s3user-akey"
#  secret_key: "s3user-skey"
#  bucket: "bucket-name"

mysql_backup_backend_use_scp: no
#mysql_backup_scp_host: ""
mysql_backup_scp_user: "root"
mysql_backup_scp_dst: "/opt/backup"
#mysql_backup_scp_identity_src: ""
mysql_backup_scp_identity_dir: "{{ mysql_backup_conf_dir }}"
mysql_backup_scp_identity_name: "id_rsa.pem"
mysql_backup_scp_identity: "{{ mysql_backup_scp_identity_dir }}/{{ mysql_backup_scp_identity_name }}"

mysql_backup_archive_prefix: "{{ mysql_backup_db }}"
mysql_backup_archive_stamp: "%F-%Hh%Mm%Ss"

mysql_backup_warn_size: "0"
mysql_backup_fail_on_warn: false
mysql_backup_gzip: no
mysql_backup_encrypt_aes: no
# key_src is just 256 bits of random: 'dd if=/dev/urandom of=aes256.key count=1 bs=32'
# Also if you want to have a string password: 'pwgen -n1 -s 32 | tr -d '\n' >aes256.key'
#mysql_backup_encrypt_aes_key_src: ""
mysql_backup_encrypt_aes_key_dir: "{{ mysql_backup_conf_dir }}"
mysql_backup_encrypt_aes_key_name: "aes256.key"
mysql_backup_encrypt_aes_key: "{{ mysql_backup_encrypt_aes_key_dir }}/{{ mysql_backup_encrypt_aes_key_name }}"
#mysql_backup_slack_webhook: ""

# set this to 'yes' if you want playbook to store the custom script
# name into 'mysql_backup_last_generated_custom_script'
mysql_backup_save_facts_about_custom_script: no
#mysql_backup_last_generated_custom_script: ""
